site_name: AeroGameFramework
site_description: Documentation for the AeroGameFramework
site_author: Stephen Leitnick
site_url: https://github.com/Sleitnick/AeroGameFramework

nav:
  - Home: index.md
  - Install & Setup: install.md
  - Services: services.md
  - Controllers: controllers.md
  - Modules: modules.md
  - Execution Model: execution_model.md
  - Module Docs:
      - Shared Modules:
        - Base64: module_docs/base64.md
        - Date: module_docs/date.md
        - Event: module_docs/event.md
        - ListenerList: module_docs/listener_list.md
        - Promise: module_docs/promise.md
        - StringUtil: module_docs/string_util.md
        - TableUtil: module_docs/table_util.md
        - Thread: module_docs/thread.md

theme:
  logo: "img/logo_64.png"
  favicon: "img/logo_32.png"
  name: material
  palette:
    primary: blue
    accent: blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - type: github
      link: https://github.com/Sleitnick/AeroGameFramework

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true